name: Generate Snake

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run automatically every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          github_user_name: miftahadzdzaudanislam
          outputs: |
            docs/pacman-contribution-graph.svg
            docs/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --staged --quiet || git commit -m "Update snake animation"
          git push
